name: books_directory
description: Books Directory app made with Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  books_data_source:
    path: packages/books_data_source
  dart_frog: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0
